-- Add new columns to protocols table
ALTER TABLE protocols 
ADD COLUMN IF NOT EXISTS content TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active',
ADD COLUMN IF NOT EXISTS difficulty TEXT NOT NULL DEFAULT 'beginner',
ADD COLUMN IF NOT EXISTS estimated_time TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS equipment TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS materials TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS safety_notes TEXT,
ADD COLUMN IF NOT EXISTS steps TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS tags TEXT;
